name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  linter:
    name: Linter
    runs-on: 'ubuntu-latest'
    if:  ${{ contains(github.repository, 'GeoGuess/Geoguess')}}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - name: Linter
      run: npm run lint
  build:
    env:
      VUE_APP_API_KEY: YOUR_GOOGLE_MAPS_API_KEY
      VUE_APP_FIREBASE_API_KEY: YOUR_FIREBASE_API_KEY
      VUE_APP_FIREBASE_PROJECT_ID: YOUR_FIREBASE_PROJECT_ID
      VUE_APP_FIREBASE_MESSAGING_SENDER_ID: YOUR_FIREBASE_MESSAGING_SENDER_ID
      VUE_APP_FIREBASE_APP_ID: YOUR_FIREBASE_APP_ID
      VUE_APP_FIREBASE_MEASUREMENT_ID: YOUR_FIREBASE_MEASUREMENT_ID
    name: Build
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - run: npm ci
    - name: Build
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: build
        # Directory containing files to upload
        path: dist
