name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  integration:
    env:
      VUE_APP_API_KEY: YOUR_GOOGLE_MAPS_API_KEY
      VUE_APP_FIREBASE_API_KEY: YOUR_FIREBASE_API_KEY
      VUE_APP_FIREBASE_PROJECT_ID: YOUR_FIREBASE_PROJECT_ID
      VUE_APP_FIREBASE_MESSAGING_SENDER_ID: YOUR_FIREBASE_MESSAGING_SENDER_ID
      VUE_APP_FIREBASE_APP_ID: YOUR_FIREBASE_APP_ID
      VUE_APP_FIREBASE_MEASUREMENT_ID: YOUR_FIREBASE_MEASUREMENT_ID
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [12]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      id: cache
      if: matrix.os != 'windows-latest'
      with:
        path: ~/.npm          
        key: ${{ matrix.os }}-node-v${{ matrix.node }}-deps-${{ hashFiles('**/package-lock.json') }}
    - name: Get npm cache directory
      id: npm-cache
      if: matrix.os == 'windows-latest'
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v2
      if: matrix.os == 'windows'
      with:
        path: ${{ steps.npm-cache.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm install

    - name: Linter
      run: npm run lint

    - name: Run unit tests
      run: npm run test:unit

    - name: Code coverage
      if:  matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v1

    - name: Build
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-node-v${{ matrix.node }}-build
        path: dist

  cypress-chrome:
    needs: integration
    env:
      VUE_APP_API_KEY:  ${{ secrets.GMAP_API_KEY }}
      VUE_APP_FIREBASE_API_KEY: YOUR_FIREBASE_API_KEY
      VUE_APP_FIREBASE_PROJECT_ID: YOUR_FIREBASE_PROJECT_ID
      VUE_APP_FIREBASE_MESSAGING_SENDER_ID: YOUR_FIREBASE_MESSAGING_SENDER_ID
      VUE_APP_FIREBASE_APP_ID: YOUR_FIREBASE_APP_ID
      VUE_APP_FIREBASE_MEASUREMENT_ID: YOUR_FIREBASE_MEASUREMENT_ID
    runs-on: ubuntu-16.04
    name: E2E on Chrome
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: 'http://localhost:8080'
          record: true
          parallel: true
          group: 'Actions chrome'
          browser: chrome
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
