name: Merge Translation

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  merge-me:
    if: github.event.pull_request.title == 'New Crowdin updates'
    name: Merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: translation
      - name: Merge me!
        uses: ridedott/merge-me-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
