name: e2e

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    if:  ${{ contains(github.repository, 'GeoGuess/Geoguess')}}    
    name: E2E on Chrome
    env:
      VUE_APP_API_KEY:  ${{ secrets.GMAP_API_KEY }}
      VUE_APP_FIREBASE_API_KEY: YOUR_FIREBASE_API_KEY
      VUE_APP_FIREBASE_PROJECT_ID: YOUR_FIREBASE_PROJECT_ID
      VUE_APP_FIREBASE_MESSAGING_SENDER_ID: YOUR_FIREBASE_MESSAGING_SENDER_ID
      VUE_APP_FIREBASE_APP_ID: YOUR_FIREBASE_APP_ID
      VUE_APP_FIREBASE_MEASUREMENT_ID: YOUR_FIREBASE_MEASUREMENT_ID
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          start: npm run serve
          wait-on: 'http://localhost:8080'
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: tests/e2e/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: tests/e2e/videos