name: Update

on:
 workflow_dispatch:
 push:
  branches: 
   - master
 schedule:
  - cron: "0 2 * * *" 

jobs:   
  checkTag:  
    runs-on: ubuntu-latest
    if:  ${{ !contains(github.repository, 'GeoGuess/Geoguess')}}
    outputs:
      lastTag: ${{ steps.lastTag.outputs.test }}
      tagActual: ${{ steps.tagActual.outputs.test }}
    steps:
     - uses: actions/checkout@v2
     - id: lastTag
       run: |
        curl "https://api.github.com/repos/GeoGuess/Geoguess/releases/latest" | grep -oP '(?<="tag_name": ")[^"]*'
     - id: tagActual
       run: |
        cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]'


