name: Update

on:
 workflow_dispatch:
 push:
  branches: 
   - master
 schedule:
  - cron: "0 2 * * *" 

jobs:
  checkUpdateAllowed:
    runs-on: ubuntu-latest
    outputs:
      ALLOWED: ${{ steps.vars.outputs.test }}   
    steps: 
      - id: vars 
        run: |
          if ["$DISABLE_CI_UPDATE" != 'true']; then
             echo ::set-output name=ALLOWED::'true'
          fi
    env:
     DISABLE_CI_UPDATE: ${{ secrets.DISABLE_CI_UPDATE }}
  
   
  checkTag:  
    runs-on: ubuntu-latest
    if:  ${{ needs.checkUpdateAllowed.outputs.ALLOWED }}
    outputs:
      lastTag: ${{ steps.lastTag.outputs.test }}
      tagActual: ${{ steps.tagActual.outputs.test }}
    steps:
     - uses: actions/checkout@v2
     - id: lastTag
       run: |
        curl "https://api.github.com/repos/GeoGuess/Geoguess/releases/latest" | grep -oP '(?<="tag_name": ")[^"]*'
     - id: tagActual
       run: |
        cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]'


  update:
    runs-on: ubuntu-latest
    needs: checkTag
    if:  ${{ needs.checkUpdateAllowed.outputs.ALLOWED }}|| ${{ needs.checkTag.outputs.lastTag }}  != ${{ needs.checkTag.outputs.tagActual }}
    steps:
      - uses: actions/checkout@v2
      - name: Test if new release
        run: |
          echo ${{ needs.checkTag.outputs.lastTag }}
          git config --local user.email "action@github.com"
          git config --local user.name "GeoGuess Updater"
          git remote add main https://github.com/GeoGuess/Geoguess
          git fetch --tags main
          git merge -X theirs --allow-unrelated-histories ${{ needs.checkTag.outputs.lastTag }}
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
