name: Update

on:
 workflow_dispatch:
 push:
  branches: 
   - master
 schedule:
  - cron: "0 2 * * *" 

jobs:   
  checkTag:  
    runs-on: ubuntu-latest
    if:  ${{ contains(github.repository, 'GeoGuess/Geoguess')}}
    outputs:
      tagActual: ${{ steps.tagActual.outputs.TAG }}
    steps:
     - uses: actions/checkout@v2
     - id: tagActual
       run: |
         VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]')
         echo ::set-output name=TAG::${VERSION}
         

  update:
    runs-on: ubuntu-latest
    needs: checkTag
    if: ${{ contains(github.repository, 'GeoGuess/Geoguess')}} || ${{ needs.checkTag.outputs.lastTag }}  != ${{ needs.checkTag.outputs.tagActual }}
    steps:
      - uses: actions/checkout@v2
      - name: Test if new release
        run: |
          echo ${{ needs.checkTag.outputs.tagActual }}
