name: Update

on:
 workflow_dispatch:
 push:
  branches: 
   - master
 schedule:
  - cron: "0 2 * * *" 

jobs:
  checkUpdateAllowed:
    runs-on: ubuntu-latest
    outputs:
      ALLOWED: ${{ steps.vars.outputs.test }}   
    steps: 
      - id: vars
        shell: bash
        run: |
          if [ "$DISABLE_CI_UPDATE" != 'true' ] ; then
             echo ::set-output name=ALLOWED::'true'
          fi
    env:
     DISABLE_CI_UPDATE: ${{ secrets.DISABLE_CI_UPDATE }}
  
   
  checkTag:  
    runs-on: ubuntu-latest
    needs: checkUpdateAllowed
    if:  ${{ needs.checkUpdateAllowed.outputs.ALLOWED }}
    outputs:
      lastTag: ${{ steps.lastTag.outputs.test }}
      tagActual: ${{ steps.tagActual.outputs.test }}
    steps:
     - uses: actions/checkout@v2
     - id: lastTag
       run: |
        curl "https://api.github.com/repos/GeoGuess/Geoguess/releases/latest" | grep -oP '(?<="tag_name": ")[^"]*'
     - id: tagActual
       run: |
        cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g' | tr -d '[[:space:]]'

